---
title: Minimalist Finance
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Varokas Panusuwan
github_username: minfinance
minima:
  date_format: "%b %-d, %Y"
header_pages:
- about2.html
markdown: kramdown
plugins:
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
